# Generated by Django 3.0.4 on 2020-03-27 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('l_number', models.AutoField(primary_key=True, serialize=False, verbose_name='课程号（pk）')),
                ('l_name', models.CharField(max_length=30, unique=True, verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程管理',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_number', models.AutoField(primary_key=True, serialize=False, verbose_name='学号（pk）')),
                ('s_name', models.CharField(help_text='学生姓名', max_length=20, verbose_name='姓名')),
                ('s_gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=6, verbose_name='性别')),
                ('ID_number', models.IntegerField(verbose_name='身份证号码')),
                ('native_place', models.CharField(max_length=30, verbose_name='家庭地址')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生管理',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_number', models.AutoField(primary_key=True, serialize=False, verbose_name='职工号（pk）')),
                ('t_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('t_gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=6, verbose_name='性别')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师管理',
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_lesson', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.Lesson', verbose_name='课程')),
                ('t_teacher', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.Teacher', unique=True, verbose_name='任课教师')),
            ],
            options={
                'verbose_name': '教学',
                'verbose_name_plural': '教学管理',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_score', models.IntegerField(default=0, verbose_name='分数')),
                ('s_lesson', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.Lesson', verbose_name='课程')),
                ('s_student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩管理',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_password', models.CharField(default='123456', max_length=20, verbose_name='密码')),
                ('a_student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户管理',
            },
        ),
    ]
