# Generated by Django 3.0 on 2020-04-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='employ_recommend',
            field=models.TextField(default='CS', max_length=30, verbose_name='就业推荐'),
        ),
    ]
