# Generated by Django 3.0.4 on 2020-03-27 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200327_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='t_teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.Teacher', verbose_name='任课教师'),
        ),
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together={('t_lesson', 't_teacher')},
        ),
    ]
