# Generated by Django 3.0.4 on 2020-03-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200327_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_number',
            field=models.AutoField(default=1911081000, primary_key=True, serialize=False),
        ),
    ]
