# Generated by Django 3.0.4 on 2020-03-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200327_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='l_credit',
            field=models.IntegerField(default=1, verbose_name='学分'),
        ),
        migrations.AddField(
            model_name='score',
            name='s_comment',
            field=models.TextField(default='', verbose_name='教师评语'),
        ),
    ]
