# Generated by Django 3.0.4 on 2020-03-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200328_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='a_student',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='management.Student', verbose_name='学生'),
        ),
    ]
