# Generated by Django 3.0.4 on 2020-03-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200328_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='ID_number',
            field=models.CharField(default='', max_length=19, verbose_name='身份证号码'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='native_place',
            field=models.CharField(default='', max_length=30, verbose_name='家庭地址'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ID_number',
            field=models.CharField(default='', max_length=19, verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='native_place',
            field=models.CharField(default='', max_length=30, verbose_name='家庭地址'),
        ),
    ]
