# Generated by Django 3.0.4 on 2020-03-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200327_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='l_teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.Teacher'),
        ),
    ]
