# Generated by Django 3.0.4 on 2020-03-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_lesson_l_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='l_teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='t_lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.Lesson', verbose_name='任课'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=6, verbose_name='性别'),
        ),
    ]
