# Generated by Django 3.0.4 on 2020-03-26 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20200327_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='lCredit',
        ),
        migrations.RemoveField(
            model_name='score',
            name='lName',
        ),
        migrations.RemoveField(
            model_name='score',
            name='lNum',
        ),
        migrations.RemoveField(
            model_name='score',
            name='lTime',
        ),
        migrations.RemoveField(
            model_name='score',
            name='sName',
        ),
        migrations.RemoveField(
            model_name='score',
            name='sNum',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='s_lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.Lesson', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='score',
            name='s_score',
            field=models.IntegerField(default=0, verbose_name='分数'),
        ),
        migrations.AddField(
            model_name='score',
            name='s_student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.Student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='l_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_name',
            field=models.CharField(max_length=10, verbose_name='姓名'),
        ),
    ]
