# Generated by Django 3.0.4 on 2020-03-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20200327_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='t_lesson',
        ),
        migrations.AddField(
            model_name='teacher',
            name='t_gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=6, verbose_name='性别'),
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_lesson', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.Lesson', verbose_name='课程')),
                ('t_teacher', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.Teacher', verbose_name='任课教师')),
            ],
            options={
                'verbose_name': '教学',
                'verbose_name_plural': '教学管理',
            },
        ),
    ]
