# Generated by Django 3.0.4 on 2020-03-26 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20200327_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_password', models.CharField(default='123456', max_length=20, verbose_name='密码')),
                ('a_student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.Student', verbose_name='学生')),
            ],
        ),
    ]
